"""Initial schema

Revision ID: a75bbfd4295f
Revises: 
Create Date: 2026-07-18 10:53:45.402808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75bbfd4295f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target_table', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_log_log_id'), 'audit_log', ['log_id'], unique=False)
    op.create_table('cities',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_index(op.f('ix_cities_city_id'), 'cities', ['city_id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_table('raw_fire_hotspots',
    sa.Column('hotspot_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('frp', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hotspot_id')
    )
    op.create_index(op.f('ix_raw_fire_hotspots_hotspot_id'), 'raw_fire_hotspots', ['hotspot_id'], unique=False)
    op.create_index(op.f('ix_raw_fire_hotspots_timestamp'), 'raw_fire_hotspots', ['timestamp'], unique=False)
    op.create_table('forecast_accuracy_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('horizon_hours', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rmse_model', sa.Float(), nullable=True),
    sa.Column('rmse_persistence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_accuracy_log_id'), 'forecast_accuracy_log', ['id'], unique=False)
    op.create_table('forecast_grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('grid_cell_id', sa.String(), nullable=True),
    sa.Column('forecast_made_at', sa.DateTime(), nullable=True),
    sa.Column('horizon_hours', sa.Integer(), nullable=True),
    sa.Column('aqi_predicted', sa.Float(), nullable=True),
    sa.Column('uncertainty_band', sa.Float(), nullable=True),
    sa.Column('physics_component', sa.Float(), nullable=True),
    sa.Column('ml_component', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_grid_forecast_made_at'), 'forecast_grid', ['forecast_made_at'], unique=False)
    op.create_index(op.f('ix_forecast_grid_id'), 'forecast_grid', ['id'], unique=False)
    op.create_table('inspectors',
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('base_lat', sa.Float(), nullable=True),
    sa.Column('base_lon', sa.Float(), nullable=True),
    sa.Column('daily_capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('inspector_id')
    )
    op.create_index(op.f('ix_inspectors_inspector_id'), 'inspectors', ['inspector_id'], unique=False)
    op.create_table('query_log',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('tools_called_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index(op.f('ix_query_log_query_id'), 'query_log', ['query_id'], unique=False)
    op.create_table('raw_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_dir', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_weather_id'), 'raw_weather', ['id'], unique=False)
    op.create_index(op.f('ix_raw_weather_timestamp'), 'raw_weather', ['timestamp'], unique=False)
    op.create_table('wards',
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('geometry', sa.Text(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('boundary_geojson', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('ward_id')
    )
    op.create_index(op.f('ix_wards_ward_id'), 'wards', ['ward_id'], unique=False)
    op.create_table('advisories',
    sa.Column('advisory_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.ward_id'], ),
    sa.PrimaryKeyConstraint('advisory_id')
    )
    op.create_index(op.f('ix_advisories_advisory_id'), 'advisories', ['advisory_id'], unique=False)
    op.create_index(op.f('ix_advisories_generated_at'), 'advisories', ['generated_at'], unique=False)
    op.create_table('anomalies',
    sa.Column('anomaly_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('investigation_note', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('confidence_statement', sa.Text(), nullable=True),
    sa.Column('human_reviewed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.ward_id'], ),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    op.create_index(op.f('ix_anomalies_anomaly_id'), 'anomalies', ['anomaly_id'], unique=False)
    op.create_index(op.f('ix_anomalies_timestamp'), 'anomalies', ['timestamp'], unique=False)
    op.create_table('attribution_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pct_vehicular', sa.Float(), nullable=True),
    sa.Column('pct_construction', sa.Float(), nullable=True),
    sa.Column('pct_industrial', sa.Float(), nullable=True),
    sa.Column('pct_burning', sa.Float(), nullable=True),
    sa.Column('pct_dust', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('signals_available_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.ward_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribution_results_id'), 'attribution_results', ['id'], unique=False)
    op.create_index(op.f('ix_attribution_results_timestamp'), 'attribution_results', ['timestamp'], unique=False)
    op.create_table('emission_sites',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('permit_ref', sa.String(), nullable=True),
    sa.Column('registered_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.ward_id'], ),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_index(op.f('ix_emission_sites_site_id'), 'emission_sites', ['site_id'], unique=False)
    op.create_table('interventions',
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('policy_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('logged_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.ward_id'], ),
    sa.PrimaryKeyConstraint('intervention_id')
    )
    op.create_index(op.f('ix_interventions_intervention_id'), 'interventions', ['intervention_id'], unique=False)
    op.create_table('raw_landuse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('pct_coverage', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.ward_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_landuse_id'), 'raw_landuse', ['id'], unique=False)
    op.create_table('stations',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.ward_id'], ),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_index(op.f('ix_stations_station_id'), 'stations', ['station_id'], unique=False)
    op.create_table('enforcement_worklist',
    sa.Column('worklist_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('feasibility_score', sa.Float(), nullable=True),
    sa.Column('assigned_inspector_id', sa.Integer(), nullable=True),
    sa.Column('justification_text', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_inspector_id'], ['inspectors.inspector_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['emission_sites.site_id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.ward_id'], ),
    sa.PrimaryKeyConstraint('worklist_id')
    )
    op.create_index(op.f('ix_enforcement_worklist_date'), 'enforcement_worklist', ['date'], unique=False)
    op.create_index(op.f('ix_enforcement_worklist_worklist_id'), 'enforcement_worklist', ['worklist_id'], unique=False)
    op.create_table('intervention_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('confidence_interval_low', sa.Float(), nullable=True),
    sa.Column('confidence_interval_high', sa.Float(), nullable=True),
    sa.Column('transferability_note', sa.Text(), nullable=True),
    sa.Column('target_city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.intervention_id'], ),
    sa.ForeignKeyConstraint(['target_city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_effects_id'), 'intervention_effects', ['id'], unique=False)
    op.create_table('raw_aqi_readings',
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('so2', sa.Float(), nullable=True),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_index(op.f('ix_raw_aqi_readings_reading_id'), 'raw_aqi_readings', ['reading_id'], unique=False)
    op.create_index(op.f('ix_raw_aqi_readings_timestamp'), 'raw_aqi_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_aqi_readings_timestamp'), table_name='raw_aqi_readings')
    op.drop_index(op.f('ix_raw_aqi_readings_reading_id'), table_name='raw_aqi_readings')
    op.drop_table('raw_aqi_readings')
    op.drop_index(op.f('ix_intervention_effects_id'), table_name='intervention_effects')
    op.drop_table('intervention_effects')
    op.drop_index(op.f('ix_enforcement_worklist_worklist_id'), table_name='enforcement_worklist')
    op.drop_index(op.f('ix_enforcement_worklist_date'), table_name='enforcement_worklist')
    op.drop_table('enforcement_worklist')
    op.drop_index(op.f('ix_stations_station_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_raw_landuse_id'), table_name='raw_landuse')
    op.drop_table('raw_landuse')
    op.drop_index(op.f('ix_interventions_intervention_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_emission_sites_site_id'), table_name='emission_sites')
    op.drop_table('emission_sites')
    op.drop_index(op.f('ix_attribution_results_timestamp'), table_name='attribution_results')
    op.drop_index(op.f('ix_attribution_results_id'), table_name='attribution_results')
    op.drop_table('attribution_results')
    op.drop_index(op.f('ix_anomalies_timestamp'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_advisories_generated_at'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_advisory_id'), table_name='advisories')
    op.drop_table('advisories')
    op.drop_index(op.f('ix_wards_ward_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_raw_weather_timestamp'), table_name='raw_weather')
    op.drop_index(op.f('ix_raw_weather_id'), table_name='raw_weather')
    op.drop_table('raw_weather')
    op.drop_index(op.f('ix_query_log_query_id'), table_name='query_log')
    op.drop_table('query_log')
    op.drop_index(op.f('ix_inspectors_inspector_id'), table_name='inspectors')
    op.drop_table('inspectors')
    op.drop_index(op.f('ix_forecast_grid_id'), table_name='forecast_grid')
    op.drop_index(op.f('ix_forecast_grid_forecast_made_at'), table_name='forecast_grid')
    op.drop_table('forecast_grid')
    op.drop_index(op.f('ix_forecast_accuracy_log_id'), table_name='forecast_accuracy_log')
    op.drop_table('forecast_accuracy_log')
    op.drop_index(op.f('ix_raw_fire_hotspots_timestamp'), table_name='raw_fire_hotspots')
    op.drop_index(op.f('ix_raw_fire_hotspots_hotspot_id'), table_name='raw_fire_hotspots')
    op.drop_table('raw_fire_hotspots')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_city_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_audit_log_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
